### ISSUE TITLE
Each entry uses up too much memory and clear doesn't clear memory used.

### ISSUE THREAD

**Issue by 240026763** [dojo90/NLogViewer#1]
This might need to be two issue reports but both relate to memory usage.

I found that the application was eating ~300MB at 500 entries and 6.5GB of memory at 23000 entries.

To quickly reproduce, change this line in TestApp MainWindow.cs:
```
Observable.Interval(TimeSpan.FromMilliseconds(10)).ObserveOnDispatcher().Subscribe(l =>
```
Also, the Pause button stops the addition of new log entries and pauses the memory growth. However, the Clear command clears the shown log entries but does not clear the memory used thus creates a memory leak.

[Edit]I re-ran the app with just 100 entries (Take(100)) which settled at roughly 69.3MB with a start memory of 27.8MB (before any entries). This generates 41.5MB for 100 records.

**Comment by dojo90** [comment]
I have tried the app and after pressing clear, you can see that the `GC` is releasing memory.

![live](https://user-images.githubusercontent.com/17551597/71241632-650aae80-230c-11ea-8036-2a1fbe50e5ff.gif)

Maybe you can give some hints, how we can boost the performance

**Comment by dojo90** [comment]
I opened a branch (https://github.com/dojo90/NLogViewer/tree/1-each-entry-uses-up-too-much-memory-and) and made some changes. Can you please test the changes? If you agree with me, I would merge it and publish a new nuget.

**Comment by dojo90** [comment]
I merged the changes and created a new nuget package
