### ISSUE TITLE
NLogViewer not updating its visual components

### ISSUE THREAD

**Issue by Rejac** [dojo90/NLogViewer#21]
Hello,

I have a TabControl with various tabs, which will be added dynamically. Each tab has a NLogViewer for displaying logs happening inside that tab. Your sample code works great when added inside xaml, but when added via code, the following behaviour occurs: 
If switched between tabs, the initial tab, which holds a programmatically created NLogViewer, is not updating its visual components compared to tabs which hold a NLogView created inside the xaml.

This is my code, to create the controls and other stuff:
```
LoggingConfiguration config = LogManager.Configuration;

var logger = LogManager.GetLogger(LoggerName);


CacheTarget target = new CacheTarget()
{
    Name = LoggerName
};
config.AddTarget(LoggerName, target);

LoggingRule loggingRule = new LoggingRule("*", LogLevel.Trace, target);

loggingRule.DefaultFilterResult = FilterResult.Ignore;
loggingRule.Filters.Add(new WhenEqualFilter()
{
    Layout = "${logger}",
    CompareTo = LoggerName,
    Action = FilterResult.Log,
    IgnoreCase = true
});

config.LoggingRules.Add(loggingRule);

LogManager.Configuration = config;

NLogViewer_ = new NLogViewer()
{
    TargetName = LoggerName,
};

TabItemLog.Content = NLogViewer_;


Task t = Task.Run(() =>
{
    for (int k = 0; k < 10000; k++)
    {
        logger.Error("error: " + k + " || " + LoggerName);
        Thread.Sleep(1000);
    }
});
```

**Comment by dojo90** [comment]
I have successfully tested with the following code:

```csharp
LoggingConfiguration config = new LoggingConfiguration();

string loggerName = "foo";

CacheTarget target = new CacheTarget
{
	Name = loggerName
};
config.AddTarget(loggerName, target);

LoggingRule loggingRule = new LoggingRule("*", LogLevel.Error, target);

//loggingRule.DefaultFilterResult = FilterResult.Ignore;
//loggingRule.Filters.Add(new WhenEqualFilter()
//{
//    Layout = "${logger}",
//    CompareTo = loggerName,
//    Action = FilterResult.Log,
//    IgnoreCase = true
//});

config.LoggingRules.Add(loggingRule);

LogManager.Configuration = config;

NLogViewer nLogViewer = new NLogViewer()
{
	TargetName = loggerName,
};

CodeBehind.Content = nLogViewer;
```

It seems there is something wrong with your 'filter'. After I commented it out, it worked.

**Comment by Rejac** [comment]
Hi Dojo,

thanks for your feedback. I have figured out, that it was not a problem with NLogViewer, with how the display was implemented. I had wrapped the page around a frame to be able to add it, but the frame killed the visual update. Removing it solved my problem.

Thank you very much.

Regards,
Rejac
