### ISSUE TITLE
TestApp appears to white after application start

### ISSUE THREAD

**Issue by jckgore** [dojo90/NLogViewer#22]
I'm having issues with this in my app resizing my window to go across all three monitors. I tried running the example in Master, but it doesn't seem to run very well - it doesn't display two logs and after a couple seconds the whole application goes white. Is the demo stable?

**Comment by dojo90** [comment]
Please provide a sample application to investigate your problem. Of course the demo application is stable.

**Comment by jckgore** [comment]
Here's what I see with the test app:

[NLogViewer.zip](https://github.com/dojo90/NLogViewer/files/4921319/NLogViewer.zip)

**Comment by dojo90** [comment]
Have a look at https://github.com/dojo90/NLogViewer/blob/master/src/NLogViewer.TestApp/MainWindow.xaml.cs#L36. This is a holdover when I ran memory leak tests. If you comment out these lines, everything should work as you expect. I will adjust this in my next release.

**Comment by dojo90** [comment]
Does this problem still exist?

**Comment by jckgore** [comment]
I didn't have a ton of time, but I pulled the latest and ran the TestApp and it appears to be working now. I'll probably attempt to integrate the package into our codebase in the next week or two.
