### ISSUE TITLE
Does it possible to create NLogViewer targets entities dynamically?

### ISSUE THREAD

**Issue by FMoralesLdG** [dojo90/NLogViewer#24]
Hi, 

I would like to create a tab control dynamically each time that a user for example download a file, this tab will include the log associated only to this task.

How can I create and isolate logs programmatic  from each of these items inserted in a controller and logs trace separately?

Any help or example about how to consume logs dynamically/programmatically for at least 2 entities would be appreciated.

**Comment by dojo90** [comment]
Below is a sample how you could create a `NLogViewer` for a task (link: https://github.com/dojo90/NLogViewer/blob/master/README.md#seperate-logger-for-a-task)

Actually it is possible to create a unique logger for a task. Maybe we should think about a factory class to create it more dynamically. So If you are interested, you can make a PR.

![preview](https://raw.githubusercontent.com/dojo90/NLogViewer/master/doc/images/newtask.gif)

```csharp
// create unique target name
var taskNumber = _RandomTaskCounter++;
string targetName = $"task{taskNumber}";
// create a unique logger
var loggerName = $"MyFoo.Logger.{taskNumber}";
var logger = LogManager.GetLogger(loggerName);

// create new CacheTarget
CacheTarget target = new CacheTarget
{
    Name = targetName
};

// get config // https://stackoverflow.com/a/3603571/6229375
var config = LogManager.Configuration;

// add target
config.AddTarget(targetName, target);

// create a logging rule for the new logger
LoggingRule loggingRule = new LoggingRule(loggerName, LogLevel.Trace, target);

// add the logger to the existing configuration
config.LoggingRules.Add(loggingRule);

// reassign config back to NLog
LogManager.Configuration = config;

// create a new NLogViewer Control with the unique logger target name
NLogViewer nLogViewer = new NLogViewer
{
    TargetName = targetName,
};

// add it to the tab control
var tabItem = new TabItem { Header = $"Task {taskNumber}", Content = nLogViewer };
TabControl1.Items.Add(tabItem);
TabControl1.SelectedItem = tabItem;

// create task which produces some output
var task = new Task(async () =>
{
    while (true)
    {
        logger.Info($"Hello from task nr. {taskNumber}. It's {DateTime.Now.ToLongTimeString()}");
        await Task.Delay(1000);
    }
});
```
