### ISSUE TITLE
Could we set up to auto clear the message when it's too many 

### ISSUE THREAD

**Issue by ceywj** [dojo90/NLogViewer#58]
too many message might cause more memory ussage , I want to know is there a way to solve this, thanks.

**Comment by dojo90** [comment]
There is already a flag `MaxCount` which you can use to limit the maximum messages in buffer. I will mark it in the readme.

https://github.com/dojo90/NLogViewer/blob/master/src/NLogViewer/Targets/CacheTarget.cs#L56

```xml
<targets async="true">
  <target xsi:type="CacheTarget" name="target1" MaxCount="500"/>
</targets>
```

**Comment by ceywj** [comment]
I fought it , thank you , we fought  also can change the colors in the setting
