### ISSUE TITLE
Performance Issue - Cache tooks long time

### ISSUE THREAD

**Issue by jeganathpv** [dojo90/NLogViewer#73]
In my case I have used both CacheTarget & FileTarget

In my case I will add 20-30k logs after that I will show some results view window.
So my tasks are completed and logs are added in files and then results are shown
But In CacheTarget, it took longer time atmost 20m for me.
Due to that I can't properly see the logs on UI NLogViewer.

Thanks

**Comment by dojo90** [comment]
Thank you for your feedback! Could you maybe create a fork and adjust it accordingly in the test app so that I can investigate the problem more closely?
