### ISSUE TITLE
upgrade to .net 5.0 breaks because of System.Reactive

### ISSUE THREAD

**Issue by LilianaHalcon** [dojo90/NLogViewer#75]
when upgrading my project to .net 5.0 I encountered an issue with the new version of System.Reactive.
System.TypeLoadException: 'Could not load type 'System.Reactive.Linq.DispatcherObservable' from assembly 'System.Reactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'.'

**Comment by Stefan-1313** [comment]
I have exactly the same problem.

**Comment by dojo90** [comment]
I have updated the library to net6 https://github.com/dojo90/NLogViewer/pull/82
